/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function bundle(options: BundleDtsOptions): BundleDtsResult;

export interface BundleDtsDiagnostic {
  message: string;
  file?: string;
  span?: Array<number>;
  severity: string;
}

export interface BundleDtsOptions {
  input: Array<string>;
  external?: Array<string>;
  cwd?: string;
  sourcemap?: boolean;
  cjsDefault?: boolean;
}

export interface BundleDtsResult {
  code: string;
  map?: string;
  warnings: Array<BundleDtsDiagnostic>;
}
