export { baseCompile } from './compiler-core/compile';
export { type CompilerOptions, type ParserOptions, type TransformOptions, type CodegenOptions, type HoistTransform, type BindingMetadata, BindingTypes, } from './compiler-core/options';
export { baseParse } from './compiler-core/parser';
export { transform, type TransformContext, createTransformContext, traverseNode, createStructuralDirectiveTransform, type NodeTransform, type StructuralDirectiveTransform, type DirectiveTransform, } from './compiler-core/transform';
export { generate, type CodegenContext, type CodegenResult, type CodegenSourceMapGenerator, type RawSourceMap, } from './compiler-core/codegen';
export { ErrorCodes, errorMessages, createCompilerError, type CoreCompilerError, type CompilerError, } from './compiler-core/errors';
export * from './compiler-core/ast';
export * from './compiler-core/utils';
export * from './compiler-core/babelUtils';
export * from './compiler-core/runtimeHelpers';
export { getBaseTransformPreset, type TransformPreset } from './compiler-core/compile';
export { transformModel } from './compiler-core/transforms/vModel';
export { transformOn } from './compiler-core/transforms/vOn';
export { transformBind } from './compiler-core/transforms/vBind';
export { noopDirectiveTransform } from './compiler-core/transforms/noopDirectiveTransform';
export { processIf } from './compiler-core/transforms/vIf';
export { processFor, createForLoopParams } from './compiler-core/transforms/vFor';
export { transformExpression, processExpression, stringifyExpression, } from './compiler-core/transforms/transformExpression';
export { buildSlots, type SlotFnBuilder, trackVForSlotScopes, trackSlotScopes, } from './compiler-core/transforms/vSlot';
export { transformElement, resolveComponentType, buildProps, buildDirectiveArgs, type PropsExpression, } from './compiler-core/transforms/transformElement';
export { transformVBindShorthand } from './compiler-core/transforms/transformVBindShorthand';
export { processSlotOutlet } from './compiler-core/transforms/transformSlotOutlet';
export { getConstantType } from './compiler-core/transforms/cacheStatic';
export { generateCodeFrame } from '@vue/shared';
export { checkCompatEnabled, warnDeprecation, CompilerDeprecationTypes, } from './compiler-core/compat/compatConfig';
