export declare const version: string;
export { reactive, ref, readonly, unref, proxyRefs, isRef, toRef, toValue, toRefs, isProxy, isReactive, isReadonly, isShallow, customRef, triggerRef, shallowRef, shallowReactive, shallowReadonly, markRaw, toRaw, effect, stop, getCurrentWatcher, onWatcherCleanup, ReactiveEffect, effectScope, EffectScope, getCurrentScope, onScopeDispose, } from '@vue/reactivity';
export { computed } from './runtime-core/apiComputed';
export { watch, watchEffect, watchPostEffect, watchSyncEffect, } from './runtime-core/apiWatch';
export { onBeforeMount, onMounted, onBeforeUpdate, onUpdated, onBeforeUnmount, onUnmounted, onActivated, onDeactivated, onRenderTracked, onRenderTriggered, onErrorCaptured, onServerPrefetch, } from './runtime-core/apiLifecycle';
export { provide, inject, hasInjectionContext } from './runtime-core/apiInject';
export { nextTick } from './runtime-core/scheduler';
export { defineComponent } from './runtime-core/apiDefineComponent';
export { defineAsyncComponent } from './runtime-core/apiAsyncComponent';
export { useAttrs, useSlots } from './runtime-core/apiSetupHelpers';
export { useModel } from './runtime-core/helpers/useModel';
export { useTemplateRef, type TemplateRef } from './runtime-core/helpers/useTemplateRef';
export { useId } from './runtime-core/helpers/useId';
export { hydrateOnIdle, hydrateOnVisible, hydrateOnMediaQuery, hydrateOnInteraction, } from './runtime-core/hydrationStrategies';
export { defineProps, defineEmits, defineExpose, defineOptions, defineSlots, defineModel, withDefaults, type DefineProps, type ModelRef, type ComponentTypeEmits, } from './runtime-core/apiSetupHelpers';
export { getCurrentInstance } from './runtime-core/component';
export { h } from './runtime-core/h';
export { createVNode, cloneVNode, mergeProps, isVNode } from './runtime-core/vnode';
export { Fragment, Text, Comment, Static, type VNodeRef } from './runtime-core/vnode';
export { Teleport, type TeleportProps } from './runtime-core/components/Teleport';
export { Suspense, type SuspenseProps } from './runtime-core/components/Suspense';
export { KeepAlive, type KeepAliveProps } from './runtime-core/components/KeepAlive';
export { BaseTransition, BaseTransitionPropsValidators, type BaseTransitionProps, } from './runtime-core/components/BaseTransition';
export { withDirectives } from './runtime-core/directives';
export { useSSRContext, ssrContextKey } from './runtime-core/helpers/useSsrContext';
export { createRenderer, createHydrationRenderer } from './runtime-core/renderer';
export { queuePostFlushCb } from './runtime-core/scheduler';
import { warn as _warn } from './runtime-core/warning';
export declare const warn: typeof _warn;
export { handleError, callWithErrorHandling, callWithAsyncErrorHandling, ErrorCodes, } from './runtime-core/errorHandling';
export { resolveComponent, resolveDirective, resolveDynamicComponent, } from './runtime-core/helpers/resolveAssets';
export { registerRuntimeCompiler, isRuntimeOnly } from './runtime-core/component';
export { useTransitionState, resolveTransitionHooks, setTransitionHooks, getTransitionRawChildren, } from './runtime-core/components/BaseTransition';
export { initCustomFormatter } from './runtime-core/customFormatter';
import { type DevtoolsHook, setDevtoolsHook as _setDevtoolsHook } from './runtime-core/devtools';
export declare const devtools: DevtoolsHook;
export declare const setDevtoolsHook: typeof _setDevtoolsHook;
import type { VNode } from './runtime-core/vnode';
import type { ComponentInternalInstance } from './runtime-core/component';
declare module '@vue/reactivity' {
    interface RefUnwrapBailTypes {
        runtimeCoreBailTypes: VNode | {
            $: ComponentInternalInstance;
        };
    }
}
export { TrackOpTypes, TriggerOpTypes } from '@vue/reactivity';
export type { Ref, MaybeRef, MaybeRefOrGetter, ToRef, ToRefs, UnwrapRef, ShallowRef, ShallowUnwrapRef, CustomRefFactory, ReactiveFlags, DeepReadonly, ShallowReactive, UnwrapNestedRefs, ComputedRef, WritableComputedRef, WritableComputedOptions, ComputedGetter, ComputedSetter, ReactiveEffectRunner, ReactiveEffectOptions, EffectScheduler, DebuggerOptions, DebuggerEvent, DebuggerEventExtraInfo, Raw, Reactive, } from '@vue/reactivity';
export type { MultiWatchSources, WatchEffect, WatchOptions, WatchEffectOptions as WatchOptionsBase, WatchCallback, WatchSource, WatchHandle, WatchStopHandle, } from './runtime-core/apiWatch';
export type { InjectionKey } from './runtime-core/apiInject';
export type { App, AppConfig, AppContext, Plugin, ObjectPlugin, FunctionPlugin, CreateAppFunction, OptionMergeFunction, } from './runtime-core/apiCreateApp';
export type { VNode, VNodeChild, VNodeTypes, VNodeProps, VNodeArrayChildren, VNodeNormalizedChildren, } from './runtime-core/vnode';
export type { Component, ConcreteComponent, FunctionalComponent, ComponentInternalInstance, SetupContext, ComponentCustomProps, AllowedComponentProps, GlobalComponents, GlobalDirectives, ComponentInstance, ComponentCustomElementInterface, } from './runtime-core/component';
export type { DefineComponent, DefineSetupFnComponent, PublicProps, } from './runtime-core/apiDefineComponent';
export type { ComponentOptions, ComponentOptionsMixin, ComponentCustomOptions, ComponentOptionsBase, ComponentProvideOptions, RenderFunction, MethodOptions, ComputedOptions, RuntimeCompilerOptions, ComponentInjectOptions, ComponentOptionsWithoutProps, ComponentOptionsWithArrayProps, ComponentOptionsWithObjectProps, } from './runtime-core/componentOptions';
export type { EmitsOptions, ObjectEmitsOptions, EmitsToProps, ShortEmitsToObject, EmitFn, } from './runtime-core/componentEmits';
export type { ComponentPublicInstance, ComponentCustomProperties, CreateComponentPublicInstance, CreateComponentPublicInstanceWithMixins, } from './runtime-core/componentPublicInstance';
export type { Renderer, RendererNode, RendererElement, HydrationRenderer, RendererOptions, RootRenderFunction, ElementNamespace, } from './runtime-core/renderer';
export type { RootHydrateFunction } from './runtime-core/hydration';
export type { Slot, Slots, SlotsType } from './runtime-core/componentSlots';
export type { Prop, PropType, ComponentPropsOptions, ComponentObjectPropsOptions, ExtractPropTypes, ExtractPublicPropTypes, ExtractDefaultPropTypes, } from './runtime-core/componentProps';
export type { Directive, DirectiveBinding, DirectiveHook, ObjectDirective, FunctionDirective, DirectiveModifiers, DirectiveArguments, } from './runtime-core/directives';
export type { SuspenseBoundary } from './runtime-core/components/Suspense';
export type { TransitionState, TransitionHooks, } from './runtime-core/components/BaseTransition';
export type { AsyncComponentOptions, AsyncComponentLoader, } from './runtime-core/apiAsyncComponent';
export type { HydrationStrategy, HydrationStrategyFactory, } from './runtime-core/hydrationStrategies';
export type { HMRRuntime } from './runtime-core/hmr';
export { withCtx, pushScopeId, popScopeId, withScopeId, } from './runtime-core/componentRenderContext';
export { renderList } from './runtime-core/helpers/renderList';
export { toHandlers } from './runtime-core/helpers/toHandlers';
export { renderSlot } from './runtime-core/helpers/renderSlot';
export { createSlots } from './runtime-core/helpers/createSlots';
export { withMemo, isMemoSame } from './runtime-core/helpers/withMemo';
export { openBlock, createBlock, setBlockTracking, createTextVNode, createCommentVNode, createStaticVNode, createElementVNode, createElementBlock, guardReactiveProps, } from './runtime-core/vnode';
export { toDisplayString, camelize, capitalize, toHandlerKey, normalizeProps, normalizeClass, normalizeStyle, } from '@vue/shared';
export { transformVNodeArgs } from './runtime-core/vnode';
import { DeprecationTypes as _DeprecationTypes } from './runtime-core/compat/compatConfig';
export type { CompatVue } from './runtime-core/compat/global';
export type { LegacyConfig } from './runtime-core/compat/globalConfig';
export declare const DeprecationTypes: typeof _DeprecationTypes;
