//! Data structures shared across generate-stage submodules.

use oxc_diagnostics::OxcDiagnostic;
use oxc_syntax::symbol::SymbolId;
use rustc_hash::{FxHashMap, FxHashSet};

use crate::link_stage::NeededKindFlags;
use crate::types::ModuleIdx;

/// An exported name with optional rename info.
#[derive(Clone)]
pub(super) struct ExportedName {
    /// The local name (used in the declaration).
    pub(super) local: String,
    /// The exported name (used in the export statement). Same as local unless renamed.
    pub(super) exported: String,
    /// Whether this specifier should be emitted with `type` modifier.
    pub(super) is_type_only: bool,
}

/// An import specifier collected from an external import.
#[derive(Clone)]
pub(super) struct ImportSpecifier {
    pub(super) local: String,
    pub(super) kind: ImportSpecifierKind,
}

#[derive(Clone)]
pub(super) enum ImportSpecifierKind {
    Namespace,
    Default,
    Named(String),
}

impl ImportSpecifierKind {
    pub(super) fn sort_key(&self) -> &str {
        match self {
            Self::Namespace => "*",
            Self::Default => "default",
            Self::Named(name) => name.as_str(),
        }
    }
}

/// An external import to be preserved in the output.
#[derive(Clone)]
pub(super) struct ExternalImport {
    pub(super) source: String,
    pub(super) specifiers: Vec<ImportSpecifier>,
    pub(super) is_type_only: bool,
    pub(super) side_effect_only: bool,
    /// When `true`, this import was created from an `export { ... } from "external"`
    /// re-export and should not be pruned by the per-module tree-shaking filter.
    pub(super) from_reexport: bool,
}

/// An `export * from "mod"` to be preserved in the output.
#[derive(Clone)]
pub(super) struct ExternalStarExport {
    pub(super) source: String,
    pub(super) is_type_only: bool,
}

/// Info for creating a namespace wrapper around a module.
pub(super) struct NamespaceWrapInfo {
    /// The namespace name, e.g. `foo_d_exports`.
    pub(super) namespace_name: String,
    /// Exported names from the wrapped module (for the namespace export list).
    pub(super) export_names: Vec<ExportedName>,
}

pub(super) struct ModuleOutput {
    pub(super) relative_path: String,
    pub(super) is_ns_wrapped: bool,
    pub(super) namespace_wrapper: Option<String>,
    pub(super) code: String,
    pub(super) map: Option<oxc_sourcemap::SourceMap>,
}

/// A single declaration/statement rendered to code, with metadata for assembly.
pub(super) struct DeclarationFragment {
    pub(super) code: String,
    pub(super) map: Option<oxc_sourcemap::SourceMap>,
    /// Symbol IDs defined by this declaration (for tree-shaking at assembly time).
    pub(super) defined_symbols: Vec<(SymbolId, NeededKindFlags)>,
    /// Export names this statement produces (used when module is entry).
    pub(super) export_names: Vec<ExportedName>,
    /// External imports introduced by this statement (from ImportDeclaration
    /// or `export { ... } from "external"`).
    pub(super) imports: Vec<ExternalImport>,
    /// Names referenced by this fragment (for import pruning at assembly time).
    pub(super) referenced_names: FxHashSet<String>,
    /// Whether this statement is an export statement (for has_any_export_statement).
    pub(super) is_export_statement: bool,
    /// Star re-exports produced by this statement.
    pub(super) star_exports: Vec<ExternalStarExport>,
    /// Bare re-export specifiers needing namespace resolution at assembly time.
    /// For `export { X }` where X may be a namespace alias (entry modules only).
    pub(super) bare_reexport_specs: Vec<BareReexportSpec>,
    /// Internal namespace star re-exports needing `namespace_wraps` at assembly.
    /// For `export * as X from "./internal"` (entry modules only).
    pub(super) internal_ns_reexports: Vec<InternalNsReexport>,
}

/// A bare `export { X }` specifier that may resolve to a namespace alias at assembly time.
#[derive(Clone)]
pub(super) struct BareReexportSpec {
    pub(super) symbol_id: Option<SymbolId>,
    pub(super) local: String,
    pub(super) exported: String,
    pub(super) is_type_only: bool,
}

/// An `export * as X from "./internal"` that needs namespace_wraps at assembly time.
#[derive(Clone)]
pub(super) struct InternalNsReexport {
    pub(super) source_module_idx: ModuleIdx,
    pub(super) exported_name: String,
    pub(super) is_type_only: bool,
}

/// All fragments for a single module, produced once during Phase 1.
pub struct ModuleFragments {
    pub(super) fragments: Vec<DeclarationFragment>,
    pub(super) relative_path: String,
    /// Imports generated by the rewriter (inline import type → namespace import, etc.).
    pub(super) rewriter_imports: Vec<ExternalImport>,
    /// Namespace wrapper blocks from InlineImportAndNamespaceRewriter.
    pub(super) ns_wrapper_blocks: String,
    /// Names re-exported via `export { X }` (no source) — for import pruning.
    pub(super) reexported_import_names: FxHashSet<String>,
    /// External namespace info for import→named conversion.
    pub(super) external_ns_info: FxHashMap<SymbolId, (String, String)>,
    /// Warnings collected during processing.
    pub(super) warnings: Vec<OxcDiagnostic>,
}

/// Pre-computed per-entry data needed for assembly.
/// Must be computed before Phase 1 (before module bodies are taken).
pub struct PrecomputedEntryData {
    pub(super) namespace_wraps: FxHashMap<ModuleIdx, NamespaceWrapInfo>,
    pub(super) namespace_aliases: FxHashMap<SymbolId, ModuleIdx>,
    pub helper_reserved_names: FxHashSet<String>,
    pub(super) needed_symbol_kinds:
        FxHashMap<ModuleIdx, Option<FxHashMap<SymbolId, NeededKindFlags>>>,
    pub(super) warnings: Vec<OxcDiagnostic>,
    /// Pre-computed star re-export results for entry modules.
    /// Key: source_module_idx from `export * from "./internal"`.
    pub(super) star_reexport_data: FxHashMap<ModuleIdx, PrecomputedStarExport>,
}

impl PrecomputedEntryData {
    /// Module indices needed by this entry.
    pub fn needed_module_indices(&self) -> impl Iterator<Item = ModuleIdx> + '_ {
        self.needed_symbol_kinds.keys().copied()
    }
}

/// Pre-computed results from `collect_module_exports` for an entry's `export *` statement.
pub struct PrecomputedStarExport {
    pub(super) exports: Vec<ExportedName>,
    pub(super) imports: Vec<ExternalImport>,
}
