name: CodSpeed

on:
  push:
    branches: [main]
  pull_request:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          shared-key: "rust-cache"
      - name: Install cargo-codspeed
        run: cargo install cargo-codspeed --locked
      - name: Build benchmarks
        run: cargo codspeed build
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          run: cargo codspeed run
